### ISSUE TITLE
 Error: undeclared identifier: 'newContext'

### ISSUE THREAD

**Issue by majj** [xmonader/nim-redisclient#1]
for Nim 0.18.1 on Windows 10:

.nimble\pkgs\redisclient-0.1.0\redisclient.nim(19, 23) Error: undeclared identifier: 'newContext'

**Comment by xmonader** [comment]
ah sorry about that, you need to build with -d:ssl I'll document and update that, sorry for the inconvenience

**Comment by majj** [comment]
it works, thanks!
